### PR TITLE
Added Discord Badge, Total Downloads Badge, Latest Release Badge

### PR DESCRIPTION
**Pull request by alfaaarex**

### CODE REVIEW

**Comment by alfaaarex** [comment]
Could you please come online in Discord?

________________________________

**Comment by mydockfinder** [comment]
我在中国是访问不了的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月7日(星期三) 中午1:56
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] Added Discord Badge, Total Downloads Badge, Latest Release Badge (#149)





 Could you please come online in Discord?
 
 ________________________________

**Comment by alfaaarex** [comment]
Is Discord not available in China?

**Comment by mydockfinder** [comment]
嗯&nbsp; 中国没有




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月7日(星期三) 中午1:59
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] Added Discord Badge, Total Downloads Badge, Latest Release Badge (#149)





 
Is Discord not available in China?
 
&mdash;

**Comment by alfaaarex** [comment]
oh, but just saying, did you join the server?

**Comment by mydockfinder** [comment]
你是说的 readme 分支吗，我加入了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月7日(星期三) 下午2:02
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] Added Discord Badge, Total Downloads Badge, Latest Release Badge (#149)





 
oh, but just saying, did you join the server?
 
&mdash;

**Comment by alfaaarex** [comment]
so you were using a VPN?
can you make it official?
We have suggestions and feedback in the server.
It is more accessible since discord has billions of users. We already have 25 members in the server within one day!

**Comment by mydockfinder** [comment]
主要我忙不过来&nbsp; 平时还要上班，我在中国也有谈论的群，有一点忙不过来




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月7日(星期三) 下午2:14
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] Added Discord Badge, Total Downloads Badge, Latest Release Badge (#149)





 
so you were using a VPN?
 can you make it official?
 We have suggestions and feedback in the server.
 It is more accessible since discord has billions of users.
 
&mdash;

**Comment by alfaaarex** [comment]
No problem. Feel free to visit it anytime!
But, just lets make it an official server!
We will get more people to Join the server!

**Comment by mydockfinder** [comment]
等我这周有时间看一下，如果可以的话我改成官方的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月7日(星期三) 下午2:21
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] Added Discord Badge, Total Downloads Badge, Latest Release Badge (#149)





 
No problem. Feel free to visit it anytime!
 But, just lets make it an official server!
 We will get more people to Join the server!
 
&mdash;

**Comment by alfaaarex** [comment]
Thanks!
Meanwhile, can I keep requesting changes to the Repository?

**Comment by mydockfinder** [comment]
可以




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月7日(星期三) 下午2:24
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder] Added Discord Badge, Total Downloads Badge, Latest Release Badge (#149)





 
Thanks!
 Meanwhile, can I keep requesting changes to the Repository?
 
&mdash;

**Pull request merged**
